import "./globals.css";
import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import { cn } from "@/lib/utils";

const libreFranklin = Libre_Franklin({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={cn(libreFranklin.className, "bg-background")}>
				{children}
			</body>
		</html>
	);
}
